/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ThreeDSpace.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-27-2016
 * 
 * XDoclet definition:
 * @struts.form name="checkOutMyCartForm"
 */
public class CheckOutMyCartForm extends ActionForm {
	private String isAddToOrder1;
	private String isAddToOrder2;
	
	public String getIsAddToOrder1() {
		return isAddToOrder1;
	}
	public void setIsAddToOrder1(String isAddToOrder1) {
		this.isAddToOrder1 = isAddToOrder1;
	}
	public String getIsAddToOrder2() {
		return isAddToOrder2;
	}
	public void setIsAddToOrder2(String isAddToOrder2) {
		this.isAddToOrder2 = isAddToOrder2;
	}

	
}