/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ThreeDSpace.struts.action;

import service.*;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import domain.*;

/**
 * MyEclipse Struts Creation date: 06-05-2016
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="comment" path="/WEB-INF/Goods.jsp"
 */
public class CommentAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		int GoodsId = Integer.parseInt(request.getParameter("GoodsId"));
		String time = request.getParameter("time");
		String comment = request.getParameter("comment");
	//	User u = (User) request.getSession().getAttribute("SignInUser");

		String userId = null;
		Cookie cookies[] = request.getCookies();// 获取cookie
		// 遍历cookie信息
		User u = (User)request.getSession().getAttribute("SignInUser");
		System.out.println("hahahaha" + u.getU_name());
		int userId2 = u.getU_id();
//		for (int i = 0; cookies != null && i < cookies.length; i++) {
//			if ("userId".equals(cookies[i].getName())) {
//				userId = cookies[i].getValue();
//			}
//		}
//		int userId2 = Integer.parseInt(userId);
		CommentService cs = new CommentService();
		cs.insertComment(userId2, GoodsId,comment, time);
		//System.out.print(time + "     " + comment + "    " + GoodsId + "   " + userId);
		
		
		
		
		
		
		request.setAttribute("GoodsId", GoodsId);

		return mapping.findForward("comment");
	}
}