/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ThreeDSpace.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import service.MyCart;
import service.MyFavorites;

/** 
 * MyEclipse Struts
 * Creation date: 03-22-2016
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GoToAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward  
	 */
	public ActionForward GoToSignUp(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("GoToSignUp");	
	}
	
<<<<<<< HEAD
=======
	public ActionForward GoToLoginRegister(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("GoToLoginRegister");	
	}
>>>>>>> 03f86a12ee4e81a41c4c70c02f0595697cb7bf3d
	public ActionForward GoToGoods(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String GoodsId=request.getParameter("GoodsId");
		request.setAttribute("GoodsId", GoodsId);
		return mapping.findForward("GoToGoods");
		
	}
	
<<<<<<< HEAD
	public ActionForward GoToCustomize(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if(request.getSession().getAttribute("SignInUser") == null){
			request.setAttribute("ErrInfo", "Please sign in or sign up first!");
			return mapping.findForward("Err");
		}else return mapping.findForward("GoToCustomize");
		
	}
	
	public ActionForward GoToShoppingCart(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if(request.getSession().getAttribute("SignInUser") == null){
			request.setAttribute("ErrInfo", "Please sign in or sign up first!");
			return mapping.findForward("Err");
		}else{
			//简单地跳转到购物车页面，直接取出购物车，不需要添加
			MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
					
=======
	public ActionForward GoToShoppingCart(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//简单地跳转到购物车页面，直接取出购物车，不需要添加
		if(request.getSession().getAttribute("SignInUser")==null){
			request.setAttribute("ErrInfo", "Please sign in or register first!");
			return mapping.findForward("Err");	
		}else{
			MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
			
>>>>>>> 03f86a12ee4e81a41c4c70c02f0595697cb7bf3d
			//准备显示，不会准备数据的话会报空指针错误
			request.setAttribute("MyCartList", myCart.ShowMyCart());
			request.setAttribute("TotalPrice", myCart.GetTotalPrice()+"");
			
<<<<<<< HEAD
			return mapping.findForward("GoToShoppingCart");
=======
			return mapping.findForward("GoToShoppingCart");	
>>>>>>> 03f86a12ee4e81a41c4c70c02f0595697cb7bf3d
		}
	}
	
	public ActionForward GoToMyOrders(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
<<<<<<< HEAD
		if(request.getSession().getAttribute("SignInUser") == null){
			request.setAttribute("ErrInfo", "Please sign in or sign up first!");
			return mapping.findForward("Err");
=======
		if(request.getSession().getAttribute("SignInUser")==null){
			request.setAttribute("ErrInfo", "Please sign in or register first!");
			return mapping.findForward("Err");	
>>>>>>> 03f86a12ee4e81a41c4c70c02f0595697cb7bf3d
		}else{
			//简单地跳转到购物车页面，直接取出购物车，不需要添加
			MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
			
			
			//准备显示，不会准备数据的话会报空指针错误
			request.setAttribute("MyCartList", myCart.ShowMyCart());
			request.setAttribute("TotalPrice", myCart.GetTotalPrice()+"");
			return mapping.findForward("GoToMyOrders");
<<<<<<< HEAD
		}
=======
		}	
>>>>>>> 03f86a12ee4e81a41c4c70c02f0595697cb7bf3d
	}
	
	public ActionForward GoToHomePage(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("GoToHomePage");
		
	}
	
	public ActionForward GoToMyFavorites(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
<<<<<<< HEAD
		if(request.getSession().getAttribute("SignInUser") == null){
			request.setAttribute("ErrInfo", "Please sign in or sign up first!");
			return mapping.findForward("Err");
=======
		if(request.getSession().getAttribute("SignInUser")==null){
			request.setAttribute("ErrInfo", "Please sign in or register first!");
			return mapping.findForward("Err");	
>>>>>>> 03f86a12ee4e81a41c4c70c02f0595697cb7bf3d
		}else{
			MyFavorites myFavorites=(MyFavorites) request.getSession().getAttribute("MyFavorites");
			//准备显示
			request.setAttribute("MyFavoritesList", myFavorites.ShowMyFavorites());
			return mapping.findForward("GoToMyFavorites");
		}
	}
<<<<<<< HEAD
	
	public ActionForward GoToSignInUp(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("GoToSignInUp");
		
	}
	
	
=======
>>>>>>> 03f86a12ee4e81a41c4c70c02f0595697cb7bf3d
}