/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ThreeDSpace.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;








import com.ThreeDSpace.struts.form.CheckOutMyCartForm;

import domain.Goods;
import domain.User;
import service.MyCart;
import service.MyFavorites;
import service.MyOrder;
import service.OrderService;




/** 
 * MyEclipse Struts
 * Creation date: 03-22-2016
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ShoppingClAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward AddToCart(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
<<<<<<< HEAD
		String GoodsId=request.getParameter("GoodsId");
		//取出购物车并添加
		MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
		myCart.AddGoodsToCart(GoodsId);
		
		//准备显示
		request.setAttribute("MyCartList", myCart.ShowMyCart());
		request.setAttribute("TotalPrice", myCart.GetTotalPrice()+"");
		return mapping.findForward("GoToCart");
=======
		if(request.getSession().getAttribute("SignInUser")==null){
			request.setAttribute("ErrInfo", "Please sign in or register first!");
			return mapping.findForward("Err");	
		}else{
			String GoodsId=request.getParameter("GoodsId");
			//取出购物车并添加
			MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
			myCart.AddGoodsToCart(GoodsId);
			
			//准备显示
			request.setAttribute("MyCartList", myCart.ShowMyCart());
			request.setAttribute("TotalPrice", myCart.GetTotalPrice()+"");
			return mapping.findForward("GoToCart");
		}	
>>>>>>> 03f86a12ee4e81a41c4c70c02f0595697cb7bf3d
	}
	
	public ActionForward DeleteFromCart(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String GoodsId=request.getParameter("GoodsId");
		//取出购物车,删除一个商品
		MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
		myCart.DeleteFromCart(GoodsId);
		//准备显示
		request.setAttribute("MyCartList", myCart.ShowMyCart());
		request.setAttribute("TotalPrice", myCart.GetTotalPrice()+"");
		return mapping.findForward("GoToCart");
	}
	
	public ActionForward UpdateShoppingNum(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String GoodsId=request.getParameter("GoodsId");
		String UpdateShoppingNum=request.getParameter("UpdateShoppingNum");
		
		MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
		myCart.updateBook(GoodsId, UpdateShoppingNum);
				
		//准备显示
		request.setAttribute("MyCartList", myCart.ShowMyCart());
		request.setAttribute("TotalPrice", myCart.GetTotalPrice()+"");
		return mapping.findForward("GoToCart");
	}
	
	public ActionForward CartAddToFavorites(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String GoodsId=request.getParameter("GoodsId");
		//取出收藏夹并添加
		MyFavorites myFavorites=(MyFavorites) request.getSession().getAttribute("MyFavorites");
		myFavorites.AddGoodsToFavorites(GoodsId);
		
		//准备显示
		//request.setAttribute("MyFavoritesList", myFavorites.ShowMyFavorites());
		
		//简单地跳转到购物车页面，直接取出购物车，不需要添加
		MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
						
		//准备显示，不会准备数据的话会报空指针错误
		request.setAttribute("MyCartList", myCart.ShowMyCart());
		request.setAttribute("TotalPrice", myCart.GetTotalPrice()+"");
		return mapping.findForward("GoToCart");
	}
	
	public ActionForward DeleteFromFavorites(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String GoodsId=request.getParameter("GoodsId");
		//取出购物车,删除一个商品
		MyFavorites myFavorites=(MyFavorites) request.getSession().getAttribute("MyFavorites");
		myFavorites.DeleteFromFavorites(GoodsId);
		//准备显示
		request.setAttribute("MyFavoritesList", myFavorites.ShowMyFavorites());
		
		return mapping.findForward("GoToFavorites");
	}
	public ActionForward HomePageAddToFavorites(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String GoodsId=request.getParameter("GoodsId");
		//取出收藏夹并添加
		MyFavorites myFavorites=(MyFavorites) request.getSession().getAttribute("MyFavorites");
		myFavorites.AddGoodsToFavorites(GoodsId);

		return mapping.findForward("GoToHomePage");
	}
	public ActionForward GoodsPageAddToFavorites(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String GoodsId=request.getParameter("GoodsId");
		//取出收藏夹并添加
		MyFavorites myFavorites=(MyFavorites) request.getSession().getAttribute("MyFavorites");
		myFavorites.AddGoodsToFavorites(GoodsId);
		
		request.setAttribute("GoodsId", GoodsId);
		return mapping.findForward("BackToGoods");
	}
	
	/*public ActionForward AddToOrder(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String GoodsId=request.getParameter("GoodsId");
		//取出购物车并添加
		MyOrder myOrder=(MyOrder) request.getSession().getAttribute("MyOrder");
		myOrder.AddGoodsToMyOrder(GoodsId);
		
		//准备显示直接取出购物车，不需要添加
		MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
		
		request.setAttribute("MyCartList", myOrder.ShowMyOrder());
		request.setAttribute("TotalPrice", myOrder.GetTotalPrice()+"");
		
		return mapping.findForward("GoToCart");
	}*/
	
	public ActionForward CheckOutMyCart(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//CheckOutMyCartForm checkOutMyCartForm=(CheckOutMyCartForm) form;
		
		//String isAddToOrder=checkOutMyCartForm.getIsAddToOrder();
		//System.out.println(isAddToOrder);
		
		//简单地跳转到订单页面，直接取出购物车，不需要添加
		//MyOrder myOrder=(MyOrder) request.getSession().getAttribute("MyOrder");
		//准备显示，不会准备数据的话会报空指针错误
		//request.setAttribute("MyOrderList", myOrder.ShowMyOrder());
		//request.setAttribute("MyOrderTotalPrice", myOrder.GetTotalPrice()+"");
		MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
		request.setAttribute("MyCartList", myCart.ShowMyCart());
		request.setAttribute("TotalPrice", myCart.GetTotalPrice()+"");
		//处理下订单的请求
		return mapping.findForward("GoToOrder");
	}
	
	public ActionForward SubmitOrder(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			OrderService orderService=new OrderService();
			//MyOrder myOrder=(MyOrder) request.getSession().getAttribute("MyOrder");
			MyCart myCart=(MyCart) request.getSession().getAttribute("MyCart");
			User user=(User) request.getSession().getAttribute("SignInUser");
			orderService.submitOrder(myCart, user);
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println(e.getMessage());
			request.setAttribute("ErrInfo", "Submit Order Error!");
			return mapping.findForward("Err");
		}
		//处理下订单的请求
		return mapping.findForward("SubmitOrderOk");
	}
}