/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ThreeDSpace.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import service.UserService;
import util.*;

import com.ThreeDSpace.struts.form.UserForm;

import domain.User;

/** 
 * MyEclipse Struts
 * Creation date: 03-21-2016
 * 
 * XDoclet definition:
 * @struts.action path="/signUp" name="userForm" scope="request" validate="true"
 */
public class SignUpAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		//String name=userForm.getUserName();
		//String email=userForm.getUserEmail();
		//System.out.println("name="+name+"  email="+email);
		
		UserService userService=new UserService();
		User user = new User();
		user.setU_name(userForm.getUserName());
		user.setU_email(userForm.getUserEmail());
		user.setU_password(MD5_test.MD5(userForm.getUserPassword()));//MD5À„∑®º”√‹
		user.setU_phoneNumber(userForm.getUserPhoneNumber());
		user.setU_address(userForm.getUserAddress());
		
		if(userService.addUser(user)){
			return mapping.findForward("SignUpOk");
		}
		request.setAttribute("ErrInfo", "SignUp Error!");
		return mapping.findForward("Err");
	}
}